<a href="https://colab.research.google.com/github/kiiza-quark/CIT-Data-science/blob/main/lesson2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import pandas as pd
import numpy as np
import statistics as st

### Iterating through numpy arrays

In [6]:
arr = np.array([23,11,22,11])
for item in arr:
    print(item)

23
11
22
11


In [9]:
#2d array

arr = np.array([
    [12,33,44],
    [33,66,77]
])

for item in arr:
    print(item)

for row in arr:
    for item in row:
        print(item)

[12 33 44]
[33 66 77]
12
33
44
33
66
77


In [10]:
arr = np.array([
    [12,33,44],
    [33,66,77]
])

for index, item in np.ndenumerate(arr):
    print(index, item)

(0, 0) 12
(0, 1) 33
(0, 2) 44
(1, 0) 33
(1, 1) 66
(1, 2) 77


In [15]:
arr = np.array([23,11,22,11])
arr2 = np.array([22,33,11, 22])
arr3 = np.array([
    [12,33,44],
    [33,66,77]
])
combination = np.concatenate((arr, arr2, arr3.flatten()))
combination

array([23, 11, 22, 11, 22, 33, 11, 22, 12, 33, 44, 33, 66, 77])